### ISSUE TITLE
投稿历史没有记录发言

### ISSUE THREAD

**Issue by forestsheep** [forestsheep911/kintoneaid#3]
在.s环境下发现没有记录发言。

在新安装的情况下，数据库正常建立，所以应该不是升级问题。
在开发模式下，用canary浏览器测试正常。chrome dev版+商店安装就有问题。所以.s也大概率不是症结所在。

等ipsec好了，测一下非.s环境再说

**Comment by forestsheep** [comment]
现在看来和.s关系不大。
又经过一些测试，让人非常不解。
所有的商店版都失败了；所有的开发版都成功了，除了chromium的mac版。
商店版无法调试，所以突破的关键可能在于chromium的mac版了。

**Comment by forestsheep** [comment]
商店版也有例外了，win的测试版，删db，再删扩展重装之后，成功了。

**Comment by forestsheep** [comment]
在我重装过一次商店版之后，好像一切都恢复正常了，貌似这个bug从未发生过。
我真是醉了。。。

**Comment by forestsheep911** [comment]
最新发现是：
过一段时间，就会记录不了投稿历史，只要一刷新，就会好。
所以很难现场调试，现在准备的做法是：
在所有可能的地方加上log，等待出问题之后查看log，找原因。

**Comment by forestsheep911** [comment]
才发现一直写在了onInstalled里面浑然不觉
